// list of viable languages
// used for data validation when registering advisor languages
// this will help avoid polluting our data
// with typos, inconsistent casing, and shorthands
// on the frontend, languages will be selectable
// via dropdown and search, making it easy to find
// the appropriate spelling

// adapted from:
// https://github.com/pandeysoni/language-list/blob/master/data.json
// with two additions:
// the original list is focused on written languages
// and only has "Chinese"
// Mandarin and Cantonese have been substituted for greater clarity
// there are more Chinese dialects than these two, but this should be sufficient

export const languageList = [
  'Afar',
  'Abkhazian',
  'Afrikaans',
  'Akan',
  'Amharic',
  'Aragonese',
  'Arabic',
  'Assamese',
  'Avar',
  'Aymara',
  'Azerbaijani',
  'Bashkir',
  'Belarusian',
  'Bulgarian',
  'Bihari',
  'Bislama',
  'Bambara',
  'Bengali',
  'Tibetan',
  'Breton',
  'Bosnian',
  'Catalan',
  'Chechen',
  'Chamorro',
  'Corsican',
  'Cree',
  'Czech',
  'Old Church Slavonic / Old Bulgarian',
  'Chuvash',
  'Welsh',
  'Danish',
  'German',
  'Divehi',
  'Dzongkha',
  'Ewe',
  'Greek',
  'English',
  'Esperanto',
  'Spanish',
  'Estonian',
  'Basque',
  'Persian',
  'Peul',
  'Finnish',
  'Fijian',
  'Faroese',
  'French',
  'West Frisian',
  'Irish',
  'Scottish Gaelic',
  'Galician',
  'Guarani',
  'Gujarati',
  'Manx',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Hiri Motu',
  'Croatian',
  'Haitian',
  'Hungarian',
  'Armenian',
  'Herero',
  'Interlingua',
  'Indonesian',
  'Interlingue',
  'Igbo',
  'Sichuan Yi',
  'Inupiak',
  'Ido',
  'Icelandic',
  'Italian',
  'Inuktitut',
  'Japanese',
  'Javanese',
  'Georgian',
  'Kongo',
  'Kikuyu',
  'Kuanyama',
  'Kazakh',
  'Greenlandic',
  'Cambodian',
  'Kannada',
  'Korean',
  'Kanuri',
  'Kashmiri',
  'Kurdish',
  'Komi',
  'Cornish',
  'Kirghiz',
  'Latin',
  'Luxembourgish',
  'Ganda',
  'Limburgian',
  'Lingala',
  'Laotian',
  'Lithuanian',
  'Latvian',
  'Malagasy',
  'Marshallese',
  'Maori',
  'Macedonian',
  'Malayalam',
  'Mongolian',
  'Moldovan',
  'Marathi',
  'Malay',
  'Maltese',
  'Burmese',
  'Nauruan',
  'North Ndebele',
  'Nepali',
  'Ndonga',
  'Dutch',
  'Norwegian Nynorsk',
  'Norwegian',
  'South Ndebele',
  'Navajo',
  'Chichewa',
  'Occitan',
  'Ojibwa',
  'Oromo',
  'Oriya',
  'Ossetian',
  'Punjabi',
  'Pali',
  'Polish',
  'Pashto',
  'Portuguese',
  'Quechua',
  'Raeto Romance',
  'Kirundi',
  'Romanian',
  'Russian',
  'Rwandi',
  'Sanskrit',
  'Sardinian',
  'Sindhi',
  'Sango',
  'Serbo-Croatian',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Samoan',
  'Shona',
  'Somalia',
  'Albanian',
  'Serbian',
  'Swati',
  'Southern Sotho',
  'Sundanese',
  'Swedish',
  'Swahili',
  'Tamil',
  'Telugu',
  'Tajik',
  'Thai',
  'Tigrinya',
  'Turkmen',
  'Tagalog',
  'Tswana',
  'Tonga',
  'Turkish',
  'Tsonga',
  'Tatar',
  'Twi',
  'Tahitian',
  'Uyghur',
  'Ukrainian',
  'Urdu',
  'Venda',
  'Vietnamese',
  'Volapük',
  'Walloon',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang',
  // 'Chinese',
  'Zulu',
  // 'Chinese' has been replaced with the below for greater clarity
  'Mandarin',
  'Cantonese',
]
