import 'reflect-metadata'
import express from 'express'
import cors from 'cors'
import session from 'express-session'
import { redis } from './utils/redis'
import connectRedis from 'connect-redis'
import { GraphQLSchema } from 'graphql'
import { ApolloServer } from 'apollo-server-express'
import { CreateContext } from './utils/context'
import {
  getComplexity,
  fieldExtensionsEstimator,
  simpleEstimator,
} from 'graphql-query-complexity'

// apollo will be generated by accepting args for the schema and context
// to allow for dependency injection/ server-side mocking of
// req/ res objects for unit testing
export const createServer = (schema: GraphQLSchema, context: CreateContext) => {
  /* --------------------------- initialize express --------------------------- */
  const app = express()

  const RedisStore = connectRedis(session)

  //app.set('trust proxy', 1) // for use in prod with nginx
  app.use(
    cors({
      origin: [process.env.CORS_ORIGIN as string],
      credentials: true,
    })
  )

  app.use(
    session({
      name: 'cid',
      store: new RedisStore({
        client: redis as any,
        disableTouch: true,
      }),
      cookie: {
        maxAge: 1000 * 60 * 60 * 24 * 365 * 10,
        httpOnly: true,
        sameSite: 'lax',
        secure: process.env.NODE_ENV === 'production', // disable for dev in localhost
        // add domain when in prod
      },
      secret: process.env.COOKIE_SECRET as string,
      resave: false,
      saveUninitialized: false,
    })
  )

  /* ---------------------------- initialize apollo --------------------------- */

  const apolloServer = new ApolloServer({
    schema,
    context,
    plugins: [
      {
        requestDidStart: () => ({
          didResolveOperation({ request, document }) {
            // limit query complexity
            const complexity = getComplexity({
              schema,
              operationName: request.operationName,
              query: document,
              variables: request.variables,
              estimators: [
                // Using fieldExtensionsEstimator is mandatory to make it work with type-graphql.
                fieldExtensionsEstimator(),
                simpleEstimator({ defaultComplexity: 1 }),
              ],
            })
            if (complexity > 200) {
              console.log(
                `query rejected for having excess complexity of ${complexity}`
              )
              throw new Error(
                `The server has rejected this request for having too great a complexity. Please revise as a more limited number of queries.`
              )
            }
          },
        }),
      },
    ],
  })

  apolloServer.applyMiddleware({ app })

  // return the app for starting the server
  // and apollo for unit testing directly against the schema
  return { app, apolloServer }
}
